eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: article
  application:
    name: lab-4-article
words: a,the

---
spring:
  profiles: sentence
  application:
    name: lab-4-sentence
server:
  port: 8020
words: notApplicable
